POST http://localhost:3001/api/recipes
Content-Type: application/json

{
    "name": "Salmon taco salad",
    "meal": "Lunch",
    "mainIngredient": "Chicken",
    "cookingTimeInMinutes": 45,
    "imageUrlId": "https://drive.google.com/file/d/1IscrtpwTC5YzdXrAxoGeByngmru51kSl/view?usp=share_link",
    "calories": 540,
    "protein": 30,
    "carbohydrates": 50,
    "fat": 15,
    "ingredients": ["100g Chicken", "30g nachos", "salad", "20g salad dressing of choice", "115g chickpeas"],
    "instructions":["1. Cook the chicken", "2. Add salad, chickpeas and chicken in to a bowl", "3. Crumble the nachos on top", "4. Top with salad dressing"]
}